scm-manager/website

src/components/features/Authentication.tsx, src/components/features/Authorization.tsx, src/components/features/Column.tsx, src/components/features/EasyInstallation.tsx, src/components/features/Feature.tsx, src/components/features/ImageColumn.tsx, src/components/features/NoDependencies.tsx, src/components/features/Plugins.tsx, src/components/features/SimpleConfiguration.tsx, src/components/features/SourceCodeManagement.tsx
Correct feature description on index page
Optimize mobile look of index page
Display images also on mobile
=> Improve index page

content/plugins/scm-activity-plugin/releases/2-0-0-rc1.yaml, content/plugins/scm-authormapping-plugin/releases/2-0-0-rc1.yaml, content/plugins/scm-branchwp-plugin/releases/2-0-0-rc1.yaml, content/plugins/scm-cas-plugin/releases/2-0-0-rc1.yaml, content/plugins/scm-ci-plugin/releases/2-0-0-rc1.yaml, content/plugins/scm-directfilelink-plugin/releases/2-0-0-rc1.yaml, content/plugins/scm-editor-plugin/releases/2-0-0-rc1.yaml, content/plugins/scm-gravatar-plugin/releases/2-0-0-rc1.yaml, content/plugins/scm-groupmanager-plugin/releases/2-0-0-rc1.yaml, content/plugins/scm-issuetracker-plugin/releases/2-0-0-rc1.yaml, content/plugins/scm-ldap-plugin/releases/2-0-0-rc1.yaml, content/plugins/scm-mail-plugin/releases/2-0-0-rc1.yaml, content/plugins/scm-pathwp-plugin/releases/2-0-0-rc1.yaml, content/plugins/scm-pushlog-plugin/releases/2-0-0-rc1.yaml, content/plugins/scm-readme-plugin/releases/2-0-0-rc1.yaml, content/plugins/scm-rest-legacy-plugin/releases/2-0-0-rc1.yaml, content/plugins/scm-script-plugin/releases/2-0-0-rc1.yaml, content/plugins/scm-ssh-plugin/releases/2-0-0-rc1.yaml, content/plugins/scm-statistic-plugin/releases/2-0-0-rc1.yaml, content/plugins/scm-support-plugin/releases/2-0-0-rc1.yaml, content/plugins/scm-tagprotection-plugin/releases/2-0-0-rc1.yaml, content/plugins/scm-webhook-plugin/releases/2-0-0-rc1.yaml, src/templates/plugin-releases.tsx
Correct formatting of dates for plugin release
=> Correct formatting of dates for plugin release

content/posts/2020-06-02-new-website/index.md
=> added new website post

content/posts/2020-06-05-scm-manager-2-0-0/index.md
Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.
=> some text changes

gatsby-config.js, package.json, yarn.lock
The page freezes on Firefox when an image is zoomed into. There is a fix available in the transient dependency of the gatsby-plugin used, but the pull request has not yet been accepted. We therefore forked the pull request and published it ourself on npm. We then used yarn resolutions in the package.json to resolve the transient dependency to the published fork. This should resolve the issue until the fix has been merged. 
=> fix critical firefox bug in zoom library

content/posts/2020-08-03-server-maintenance/index.md
Adds server maintenance blog post.
=> adds server maintenance blog post

gatsby-config.js, src/components/ReleaseFeedNote.tsx, src/pages/download/archive.tsx, src/templates/download.tsx
This pr adds a feed for releases at `/download/rss.xml`.
=> RSS Feed for releases

Jenkinsfile
Add mail notification to jenkins post step to notify team about failed build.
=> Add mail notification step to Jenkinsfile

src/pages/imprint.tsx
Expand provider identification on imprint
=> Expand provider identification on imprint

content/plugins/categories.yaml, src/components/plugins/Categories.tsx
Remove empty plugin categories
=> Remove empty plugin categories

content/plugins/categories.yaml, src/components/plugins/Categories.tsx, src/templates/category.tsx
Add new category for all plugins
=> Add new category for all plugins

src/templates/doc.tsx
Correct preselected language and version on doc pages
=> Correct preselected language and version on doc pages

gatsby-config.js, package.json, yarn.lock
Allow plantuml diagrams in code blocks
=> Allow plantuml diagrams in code blocks

content/plugins/scm-scw-plugin/plugin.yml, content/plugins/scm-scw-plugin/releases/1-1-0.yaml, src/components/Plugin.tsx, src/templates/category.tsx, src/types/plugin.ts
Add plugin yml for Secure Code Warrior Plugin. This plugin will be available through the SCM-Manager plugin center by linking to the installation instructions on myCloudogu.
**Reviewer**:
=> Enable cloudogu plugins

content/posts/2012-01-03-scm-hgnested-plugin/index.md, content/posts/2021-08-04-hg-survey/index.md
Create mercurial survey blog post
=> Create mercurial survey blog post

src/components/NavigationSettings.tsx
Switching version in the plugin documentation leads to 404 error
**Reviewer**:
=> Switching version in the plugin documentation leads to 404 error

content/posts/2021-09-04-community-forum/index.md, src/pages/support.tsx
Add community forum link to support page
=> Add community forum link to support page

gatsby-node.js, src/components/WarningBanner.tsx, src/templates/doc.tsx, src/templates/plugin-docs.tsx
Add banner on top of outdated documentation pages that links to the most recent version of that page.
**Reviewer**:
=> add link to latest version to doc pages

content/posts/2021-09-29-scm-manager-public-scm/index.md
Create blogpost about the new public showcases
=> Create blogpost for public showcases

content/posts/2021-11-11-java-11/index.md
Adds a blog post to notify about the upcoming transition to Java 11.
=> Add blog post for Java 11

content/posts/2021-12-13-log4shell/index.md
Update the post regarding log4j and anounce v2.27.3.
=> Update post regarding log4j/logback

content/posts/2021-12-23-scm-manager-2-28-0/index.md, content/posts/2022-01-03-scm-manager-plugin-development/index.md
Add blog post to recap 2021 and mention our highlights of 2021
=> Add blog post for 2021 recap

src/pages/data-processing.tsx
Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue. Please ensure the "what" and "why" are explained properly in this description as it will be used as the commit description on squashing your pull request commits. 
**Reviewer**:
=> Add data processing page

content/plugins/scm-htpasswd-plugin/plugin.yml
Migrated scm-passwd-plugin from scm-manager 1.x to 2.x. Based on scm-ldap-plugin. This will fix [issue 1961](https://github.com/scm-manager/scm-manager/issues/1961).
Plugin repository: https://github.com/ggrandes/scm-htpasswd-plugin
**Reviewer**:
=> Migrated scm-htpasswd-plugin for scm-manager 2.x

content/plugins/scm-pushevent-plugin/plugin.yml
Publish scm-pushevent-plugin. The plugin sends meta information about push events to an REST-endpoint.
Link to plugin repository: https://github.com/cloudogu/scm-pushevent-plugin
**Reviewer**:
=> Publish scm-pushevent-plugin.

content/plugins/scm-redmine-plugin/plugin.yml
Adjust redmine plugin description to point out it is also compatible with EasyRedmine.
=> Adjust redmine plugin description

content/cli/releases/0-1-0.yaml, gatsby-node.js, package.json, scripts/collect-cli-content.js, scripts/collect-content.js, scripts/config.js, src/components/AlertsNotification.tsx, src/components/Download.tsx, src/components/DownloadCli.tsx, src/components/WarningBanner.tsx, src/layout/NavbarMenu.tsx, src/pages/cli/archive.tsx, src/pages/download/archive.tsx, src/templates/cli-install.tsx, src/templates/cli.tsx, src/templates/doc.tsx, src/templates/plugin-docs.tsx, yarn.lock
Add CLI Client pages to website. The CLI Client can be downloaded for many different os/arch combinations. To use the CLI Client follow the related instructions and make sure the CLI may reach your running SCM-Manager server. 
**Reviewer**:
=> Add CLI Client to Website

content/plugin-sets/office/description_en.yml
Unifies case after bullet points for Englisch language.
**Reviewer**:
=> Fix case after bullet points

src/layout/Footer.tsx, src/pages/imprint.tsx, src/pages/privacy.tsx
Update privacy policy
**Reviewer**:
=> Update privacy policy

src/components/SEO.tsx, src/layout/Footer.tsx, src/pages/privacy.tsx
Update tracking cookie consent
**Reviewer**:
=> Update tracking cookie consent
